[default]
DEBUG = false
SQLALCHEMY_DATABASE_URI = 'sqlite:///development.db'
TITLE = "lhama"
SECRET_KEY = "jadkfbsdkjbfbh"
PASSWORD_SCHEMES = ['pbkdf2_sha512', 'md5_crypt']
EXTENSIONS = [
    "lhama.ext.database:init_app",
    "lhama.ext.commands:init_app",
    "lhama.ext.configuration:init_app",
    "lhama.ext.auth:init_app",
    "lhama.blueprints.restapi:init_app"
]

